#!/bin/bash
# Default: 4 sessions of 25m work + 5m break
sessions=4
work_mins=25
break_mins=5

for ((i=1; i<=sessions; i++)); do
    echo "🚀 Work Session $i/$sessions | $(date +%H:%M)"
    labt -S $work_mins -t "Good job! Time to rest!" -b "Mayushii wants tea!"

    exit_code=$?
    if [[ $exit_code -eq 2 ]]; then # labt returns code 2 when timer is interrupted with ctrl+c by user
        exit 2
    fi
    
    echo "☕ Break Time! | $(date +%H:%M)"
    [[ $i -lt $sessions ]] && labt -S $break_mins -t "Back to experiments!" -b "Tutturu!~ Time to focus!"
done

echo "🎉 All sessions complete!"